# Generated by Django 5.0.1 on 2026-02-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("UPLOAD", "PDF/Image Upload"),
                            ("MANUAL", "Manual Entry"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Processing"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="statements/%Y/%m/"
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("merchant_name", models.CharField(blank=True, max_length=255)),
                ("processor_name", models.CharField(blank=True, max_length=100)),
                ("statement_period_start", models.DateField(blank=True, null=True)),
                ("statement_period_end", models.DateField(blank=True, null=True)),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("requires_review", models.BooleanField(default=False)),
                ("extraction_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Statement",
                "verbose_name_plural": "Merchant Statements",
                "db_table": "statements_merchantstatement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatementData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_volume", models.DecimalField(decimal_places=2, max_digits=15)),
                ("transaction_count", models.IntegerField()),
                (
                    "visa_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("visa_count", models.IntegerField(default=0)),
                (
                    "mastercard_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("mastercard_count", models.IntegerField(default=0)),
                (
                    "amex_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("amex_count", models.IntegerField(default=0)),
                (
                    "discover_volume",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("discover_count", models.IntegerField(default=0)),
                (
                    "interchange_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "assessment_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "processing_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monthly_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "effective_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="statements.merchantstatement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statement Data",
                "verbose_name_plural": "Statement Data",
                "db_table": "statements_statementdata",
            },
        ),
    ]
