# Generated by Django 5.0.1 on 2026-02-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementdata",
            name="interac_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="statementdata",
            name="interac_volume",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
