# Generated by Django 5.0.1 on 2026-02-06 12:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("statements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Competitor/Processor name (e.g., Chase, Square, Stripe)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Competitor logo image",
                        null=True,
                        upload_to="competitors/logos/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the competitor"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this competitor is actively used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Competitor",
                "verbose_name_plural": "Competitors",
                "db_table": "analyses_competitor",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        help_text="DBA (Doing Business As) name", max_length=255
                    ),
                ),
                (
                    "business_address",
                    models.TextField(help_text="Full business address"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact person name",
                        max_length=255,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the merchant"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Agent who created this merchant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
                "db_table": "analyses_merchant",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("COMPLETED", "Completed"),
                            ("SUBMITTED", "Submitted"),
                        ],
                        default="DRAFT",
                        help_text="Current status of the analysis",
                        max_length=20,
                    ),
                ),
                (
                    "current_processing_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current processing rate percentage (e.g., 2.50 for 2.5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "current_monthly_fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current monthly fees in dollars",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_transaction_fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current per-transaction fees in dollars",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly transaction volume in dollars",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "monthly_transaction_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of transactions per month",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Agent notes and observations"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated merchant statement (if uploaded)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="statements.merchantstatement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Agent who created this analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competitor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current payment processor/competitor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="analyses.competitor",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        help_text="Merchant being analyzed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="analyses.merchant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis",
                "verbose_name_plural": "Analyses",
                "db_table": "analyses_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(
                fields=["user", "-created_at"], name="analyses_me_user_id_d0de37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(
                fields=["business_name"], name="analyses_me_busines_fe6c62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["user", "-created_at"], name="analyses_an_user_id_bca6d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(
                fields=["merchant", "-created_at"],
                name="analyses_an_merchan_ba4b3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysis",
            index=models.Index(fields=["status"], name="analyses_an_status_b5c59e_idx"),
        ),
    ]
