# Generated by Django 5.0.1 on 2026-02-09 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Device name (e.g., "Clover Flex", "Clover Mini")',
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DEVICE", "Device"),
                            ("ACCESSORY", "Accessory"),
                            ("GATEWAY", "Gateway"),
                        ],
                        help_text="Device category",
                        max_length=20,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text='Device type/model (e.g., "Flex", "Mini", "Station Duo")',
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Device description and features"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Device image",
                        null=True,
                        upload_to="devices/",
                    ),
                ),
                (
                    "lease_price_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum monthly lease price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "lease_price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum monthly lease price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "purchase_price_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum one-time purchase price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "purchase_price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum one-time purchase price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device is available for selection",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Device Catalog Item",
                "verbose_name_plural": "Device Catalog Items",
                "db_table": "analyses_devicecatalogitem",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SaaSCatalogItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        help_text='SaaS plan name (e.g., "Clover Essentials", "Clover Register")',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Plan description and features"
                    ),
                ),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly subscription price",
                        max_digits=10,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Plan features as JSON (e.g., {"max_devices": 5, "inventory": true})',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is available for selection",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SaaS Catalog Item",
                "verbose_name_plural": "SaaS Catalog Items",
                "db_table": "analyses_saascatalogitem",
                "ordering": ["sort_order", "plan_name"],
            },
        ),
        migrations.CreateModel(
            name="ProposedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, help_text="Number of devices"),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[("LEASE", "Lease"), ("PURCHASE", "Purchase")],
                        help_text="Lease or purchase",
                        max_length=10,
                    ),
                ),
                (
                    "selected_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Selected price (monthly for lease, one-time for purchase)",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this device proposal",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="Analysis this device proposal belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_devices",
                        to="analyses.analysis",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        help_text="Device from the catalog",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="analyses.devicecatalogitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposed Device",
                "verbose_name_plural": "Proposed Devices",
                "db_table": "analyses_proposeddevice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposedSaaS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="Number of subscriptions/additional devices",
                    ),
                ),
                (
                    "monthly_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total monthly cost for this SaaS item",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this SaaS proposal",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="Analysis this SaaS proposal belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_saas",
                        to="analyses.analysis",
                    ),
                ),
                (
                    "saas_plan",
                    models.ForeignKey(
                        help_text="SaaS plan from the catalog",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proposals",
                        to="analyses.saascatalogitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proposed SaaS",
                "verbose_name_plural": "Proposed SaaS",
                "db_table": "analyses_proposedsaas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantHardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("POS_TERMINAL", "POS Terminal"),
                            ("CARD_READER", "Card Reader"),
                            ("PRINTER", "Printer"),
                            ("SCANNER", "Scanner"),
                            ("SOFTWARE", "Software"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of hardware/software item",
                        max_length=30,
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text='Name of the hardware/software (e.g., "Square Terminal")',
                        max_length=255,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text='Provider/vendor name (e.g., "Square", "Clover")',
                        max_length=100,
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY_LEASE", "Monthly Lease"),
                            ("MONTHLY_SUBSCRIPTION", "Monthly Subscription"),
                            ("ONE_TIME_PURCHASE", "One-Time Purchase"),
                            ("PER_TRANSACTION", "Per Transaction"),
                        ],
                        help_text="Type of cost structure",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost amount in dollars",
                        max_digits=10,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, help_text="Number of units"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this hardware/software",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="Analysis this hardware cost belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_costs",
                        to="analyses.analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Hardware",
                "verbose_name_plural": "Merchant Hardware",
                "db_table": "analyses_merchanthardware",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis", "-created_at"],
                        name="analyses_me_analysi_5335f7_idx",
                    ),
                    models.Index(
                        fields=["item_type"], name="analyses_me_item_ty_edba38_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OneTimeFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION", "Application Fee"),
                            ("DEPLOYMENT", "Deployment Fee"),
                            ("SHIPPING", "Shipping Fee"),
                            ("INSURANCE", "Insurance Fee"),
                            ("SETUP", "Setup Fee"),
                            ("OTHER", "Other Fee"),
                        ],
                        help_text="Type of one-time fee",
                        max_length=20,
                    ),
                ),
                (
                    "fee_name",
                    models.CharField(
                        help_text="Name/description of the fee", max_length=255
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fee amount in dollars",
                        max_digits=10,
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False, help_text="Whether this fee is optional"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this fee"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="Analysis this fee belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onetime_fees",
                        to="analyses.analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "One-Time Fee",
                "verbose_name_plural": "One-Time Fees",
                "db_table": "analyses_onetimefee",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis", "fee_type"],
                        name="analyses_on_analysi_b99486_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="analyses_on_created_d3dcf4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PricingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("COST_PLUS", "Cost-Plus (Interchange+)"),
                            ("I_PLUS", "iPlus"),
                            ("DISCOUNT_RATE", "Discount Rate"),
                            ("FLAT", "Flat Rate"),
                        ],
                        help_text="Type of pricing model",
                        max_length=20,
                    ),
                ),
                (
                    "is_selected",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the selected pricing model for the proposal",
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Markup percentage for cost-plus/iPlus (e.g., 0.50 for 0.5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "basis_points",
                    models.IntegerField(
                        blank=True,
                        help_text="Basis points markup for cost-plus model",
                        null=True,
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Discount rate percentage (e.g., 2.50 for 2.5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "per_transaction_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Per-transaction fee in dollars (e.g., 0.10 for $0.10)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "monthly_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly fee in dollars",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this pricing model",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        help_text="Analysis this pricing model belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_models",
                        to="analyses.analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Model",
                "verbose_name_plural": "Pricing Models",
                "db_table": "analyses_pricingmodel",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["analysis", "is_selected"],
                        name="analyses_pr_analysi_40ad4d_idx",
                    ),
                    models.Index(
                        fields=["model_type"], name="analyses_pr_model_t_4d7c21_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pricingmodel",
            constraint=models.UniqueConstraint(
                fields=("analysis", "model_type"), name="unique_analysis_model_type"
            ),
        ),
        migrations.AddIndex(
            model_name="proposeddevice",
            index=models.Index(
                fields=["analysis", "-created_at"],
                name="analyses_pr_analysi_7846be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proposedsaas",
            index=models.Index(
                fields=["analysis", "-created_at"],
                name="analyses_pr_analysi_9177be_idx",
            ),
        ),
    ]
