# Generated by Django 5.0.1 on 2026-02-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0002_devicecatalogitem_saascatalogitem_proposeddevice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="amex_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly Amex volume in dollars (for Discount Rate per-brand calculation)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="interac_txn_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of Interac debit transactions per month ($0.04/txn in Blockpay proposals)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="interchange_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly interchange (pass-through) total in dollars — from statement (used in Cost Plus / iPlus proposals)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="mc_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly Mastercard credit volume in dollars (for Discount Rate per-brand calculation)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="visa_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Monthly Visa credit volume in dollars (for Discount Rate per-brand calculation)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="amex_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Amex base discount rate %. Blockpay default: 2.65%",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="billback_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Non-qualified/billback surcharge % on non-qualifying transactions. Default: 0.25%",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="card_brand_fee_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Card brand fee % on credit volume (Cost Plus only). Default: 0.15%. Do NOT use for iPlus.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="mc_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Mastercard base discount rate %. Blockpay default: 1.38%",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="nonqualified_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated % of monthly volume that is non-qualified (keyed, CNP, premium). e.g., 15 for 15%",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="program_discount_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Program discount % billed to merchant on total ticket (sale + surcharge). e.g., 2.343",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="surcharge_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Surcharge % charged to cardholder on eligible credit transactions (e.g., 2.40)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pricingmodel",
            name="visa_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Visa base discount rate %. Blockpay default: 1.36%",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="monthly_transaction_count",
            field=models.IntegerField(
                blank=True,
                help_text="Total number of credit transactions per month",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodel",
            name="basis_points",
            field=models.IntegerField(
                blank=True,
                help_text="Markup in basis points (informational; 10 bps = 0.10%)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodel",
            name="discount_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Fallback discount rate % if per-brand rates (visa_rate/mc_rate/amex_rate) are not set",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodel",
            name="markup_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Blockpay markup % on credit volume. Cost Plus default: 0.10%; iPlus default: 0.25%",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("COST_PLUS", "Cost-Plus (Interchange+)"),
                    ("I_PLUS", "iPlus"),
                    ("DISCOUNT_RATE", "Discount Rate (Billback)"),
                    ("SURCHARGE", "Surcharge Program"),
                ],
                help_text="Type of pricing model",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodel",
            name="monthly_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed monthly fee in dollars (account fee, PCI program, etc.)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodel",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes, assumptions used, or override justification",
            ),
        ),
        migrations.AlterField(
            model_name="pricingmodel",
            name="per_transaction_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Interac debit per-transaction fee in dollars. Blockpay default: $0.04",
                max_digits=6,
                null=True,
            ),
        ),
    ]
