# Generated by Django 5.0.1 on 2026-02-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0003_add_pricing_fields_and_statement_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysis",
            name="generated_pdf",
            field=models.FileField(
                blank=True,
                help_text="Generated Blockpay proposal PDF",
                null=True,
                upload_to="proposals/",
            ),
        ),
        migrations.AddField(
            model_name="analysis",
            name="generated_pdf_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the proposal PDF was last generated",
                null=True,
            ),
        ),
    ]
